language: python
python:
  - "2.6"
  - "2.7"

cache:
 directories:
  - $HOME/.cache/pip

install: "pip install -r requirements.txt"
script:
 - "trial --reporter=text --rterrors packetmq.test.MemServerTestCase"
 - "trial --reporter=text --rterrors packetmq.test.PacketRegistryTestCase"
 - "trial --reporter=text --rterrors packetmq.test.TCPServerTestCase"
